apiVersion: gandelm.com/v1
kind: Gandelm
metadata:
  name: gandelm-sample
spec:
  endpoint: https://example.com
  entrypoint: https://example.com/entry
  external_links:
    - title: 'core-api'
      url: https://gandelm-sample.core-api.dev.example.com
    - title: '管理ツール'
      url: https://gandelm-sample.admin.dev.example.com
