---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - gandelm.com
  resources:
  - gandelmcatalogs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gandelm.com
  resources:
  - gandelmcatalogs/finalizers
  verbs:
  - update
- apiGroups:
  - gandelm.com
  resources:
  - gandelmcatalogs/status
  verbs:
  - get
  - patch
  - update
