## Append samples of your project ##
resources:
- v1_gandelmcatalog.yaml
- v1_gandelm.yaml
- v1_gandelmlabel.yaml
- v1_gandelmversion.yaml
- v1_gandelmworkload.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
